### ISSUE TITLE
How to install the bigarray library (on macOS)?

### ISSUE THREAD

**Issue by vyorkin** [diml/memory-access-bench#1]
I'm trying to figure out how to use the `ppx_bench` by looking at your example, but getting the following error:
```
dune build main.exe
File "mem_bench.ml", line 141, characters 29-64:
Error: Unknown builtin primitive "%store32"
make: *** [all] Error 1
```
I guess it is due to missing the `bigarray` library? If so -- do you know where/how can I get it?

**Comment by diml** [comment]
I used a patched compiler for this example. You can delete all the code that uses `"%storexxx"` and the build should succeed.

**Comment by vyorkin** [comment]
Thank you!
